### PR TITLE
Add copyright, updated privacy policy

### PR DESCRIPTION
**Pull request by MattIPv4**

### CODE REVIEW

**Comment by MattIPv4** [comment]
Note to self, figure out nice wrapping on mobile (or change the heading)

**Comment by MattIPv4** [comment]
Other note to self, probably needs legal review

**Comment by pjeweb** [comment]
> Note to self, figure out nice wrapping on mobile (or change the heading)

hyphens-auto should do the trick. has good browser support now. https://tailwindcss.com/docs/hyphens

**Comment by MattIPv4** [comment]
Ended up just going with standard word breaking -- hyphens causes all words to be hyphenated, rather than preferring standard breaking rules.

**Review by pjeweb — APPROVED** [review]

**Pull request merged**
