### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pjeweb**
## Describe your changes

Updates many dependencies (minor and patch only). It also uses `pnpm` scripts instead of `npx` to run lint-staged in the commit hook.

## Notes for testing your change

Basically check everything still works.

### CODE REVIEW

**Comment by MattIPv4** [comment]
Worth pushing this to the preview branch so we can test the bot and site auth?

**Comment by pjeweb** [comment]
> Worth pushing this to the preview branch so we can test the bot and site auth?

sure its on preview.alveus.gg now and the bot in alveusgg

**Review by MattIPv4 — APPROVED** [review]
All seems to be functioning still.

Any major updates pending that need looking at?

**Comment by pjeweb** [comment]
> Any major updates pending that need looking at?

no we are pretty up-to-date

**Pull request merged**
