### PR TITLE
Add social + ambassador redirects

### LINKED ISSUE #178: Redirects for ambassadors
I think it would be nice to have `/x` redirect to `/ambassadors/x` so we could link them in SE commands etc.

With the .gg domain: `https://alveus.gg/fenn`

### PR DESCRIPTION
**Pull request by MattIPv4**
Resolves #178

### CODE REVIEW

**Comment by MattIPv4** [comment]
@pjeweb I do believe the answer may be no, doing redirects this way does not work

**Comment by pjeweb** [comment]
i'm at a loss then. i would probably just keep them in two places and maybe add a bit of jsdoc to at least somewhat use types to check they match?!

```javascript
/** @type {import("./data/ambassadors.mjs").AmbassadorKey[]} */
const ambassadorNames = ["abbott", "appa", "barbaraBakedBean", "bb", …

/** @type {import("next").NextConfig} */
const config = {
  …
  redirects: async () => [
    ...ambassadorNames.map((name) => ({
      source: "/" + name,
      destination: "/ambassadors/" + name,
      permanent: false,
    })),
```

**Review by pjeweb — APPROVED** [review]
nice solution!

**Comment by MattIPv4** [comment]
It's not the greatest as it adds more build tooling, but esbuild was already in the toolchain for tsup afaik, so not the worst.

**Comment by pjeweb** [comment]
yeah does not feel too bad. i was thinking we might also use what tailwind introduced in 3.3 to compile JIT:
https://github.com/unjs/jiti

**Pull request merged**
