### PR TITLE
Higher res henrique pic

### PR DESCRIPTION
**Pull request by pjeweb**

### CODE REVIEW

**Comment by MattIPv4** [comment]
```
~/WebstormProjects/alveusgg/alveusgg main !1 ❯ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   apps/website/src/assets/ambassadors/henrique/01.jpg

no changes added to commit (use "git add" and/or "git commit -a")
```

I was literally just doing the same thing 😂

**Review by MattIPv4 — DISMISSED** [review]

**Comment by pjeweb** [comment]
might need to crop it differently headless chicken

**Comment by MattIPv4** [comment]
Ah yes, didn't consider that. Just lop some of the grass off the bottom

**Comment by MattIPv4** [comment]
👀 It looks like a lot of resolution was lost in the crop?

**Comment by pjeweb** [comment]
should have just waited for you to do it ;) time to go to bed

**Comment by MattIPv4** [comment]
All good, I'll approve this once it builds and merge assuming this looks good

**Review by MattIPv4 — APPROVED** [review]

**Pull request merged**
