### PR TITLE
Add Filian collab

### PR DESCRIPTION
**Pull request by MattIPv4**
## Describe your changes

Adds the most recent collaboration, Filian

## Notes for testing your change

Video is correct, date is correct, name/link are correct

### CODE REVIEW

**Comment by pjeweb** [comment]
No way we can get all the content id music muted. I don't think we can embed this collab ...

**Comment by MattIPv4** [comment]
Hm, yeah. How do you think we should handle it? Should we essentially just leave it as-is and allow the YouTube frame to open the 'Watch on YouTube' link, or should we add a prop to actively note this can't be embedded? If the prop, what should it do?

**Comment by pjeweb** [comment]
I don't think the link "Watch on YT" actually works? I think the event get caught somewhere.

> If the prop, what should it do?

We could add our own "Video can't be embedded, watch on youtube.com/v/xxx" thingy, but that sounds like a lot of work for pretty much no benefit. Other idea would be to disable the lightbox trigger and just open it directly on youtube. Not great UX, but i might prefer that and it should be fairly easy?!

**Comment by MattIPv4** [comment]
> I don't think the link "Watch on YT" actually works? I think the event get caught somewhere.

I just need to adjust the sandbox for the iframe and it'll work.

> Other idea would be to disable the lightbox trigger and just open it directly on youtube. Not great UX, but i might prefer that and it should be fairly easy?!

Yeah, that'd also work. My only hesitation is it might be confusing to the user that some show in a modal and some don't. I'm leaning towards the current behaviour, but with the sandbox updated so the link works?

**Review by pjeweb — DISMISSED** [review]

**Review by pjeweb — APPROVED** [review]

**Pull request merged**
