### PR TITLE
Standardise icons and icon sources

### LINKED ISSUE #80: Standardise icons and icon sources
We should standardise how we keep and use icons.

Currently we have:
- `src/icons/xxx.tsx` (inline svg icons as react components)
- `src/assets/icons/xxx.svg` (svg icons, included via URL)
- `simple-icons` (npm dep; simple icons for various brands, included via URL)
- `@heroicons/react`(npm dep; icon pack related to tailwind/tailwind ui, included via URL)

### PR DESCRIPTION
**Pull request by tomheaton**
Standardise icons and icon sources (closes #80)

- `src/icons/xxx.tsx` (inline svg icons as react components)
- ~~`src/assets/icons/xxx.svg` (svg icons, included via URL)~~
- ~~`simple-icons` (npm dep; simple icons for various brands, included via URL)~~
- ~~`@heroicons/react` (npm dep; icon pack related to tailwind/tailwind ui, included via URL)~~

### CODE REVIEW

**Comment by MattIPv4** [comment]
👀 There's still `@heroicons/react` in the mix

**Comment by tomheaton** [comment]
my bad, just made sure it was referencing issue

**Comment by tomheaton** [comment]
these are the remaining heroicons

arrowpath (outline)
trash
arrowdowntray
ellipsishorizontal
pencil (outline)
arrowpath
xcircle
archivebox
bolt
eye (outline)
trash (outline)
arrowdown
check
plus
chevronupdown
globealt (outline)
bars3 (outline)
xmark (outline)
bellalert
arrowuptray
share
videocamera
exclamationtriangle
arrowuponsquarestack
informationcircle
minuscircle (outline)
checkcircle
minus
arrowdown
arrowspointingin
arrowspointingout
arrowup
envelope (outline)

**Comment by pjeweb** [comment]
tbh i would not mind keeping the dep for now as long as we only use it for admin things. in the long term I would probably wanna use a "proper" ui framework for the admin ui like Radix (or shadcn/ui).

**Comment by MattIPv4** [comment]
I wonder if there is a better library we can use that gives us everything we need and avoid needing to have some icons in-repo? (It also worries me a bit that we have random icons in-code that aren't attributed to their source).

I realise its somewhat cliche, but perhaps font-awesome? They're normally pretty good at having utility icons as well as brands.

**Comment by tomheaton** [comment]
shadcn/ui is great

as for icons, I can make everything font awesome or similar

**Comment by MattIPv4** [comment]
That also works for me 👍 It'd be nice to make sure all the icons are attributed then, though

**Comment by tomheaton** [comment]
can you let me know where the current ones are from and i will make sure all the new ones say heroicons?

**Comment by MattIPv4** [comment]
I'm not sure where most of the current ones are from to be honest, I suspect random from all over the internet -- as you're going through, perhaps replace any that you can with attributable heroicons ones, and mark the rest as unattributed for now?

**Comment by tomheaton** [comment]
sure thing

**Comment by tomheaton** [comment]
let me know what you think

**Comment by MattIPv4** [comment]
```
./src/components/admin/notifications/NotificationsLive.tsx:93:23
Type error: Type '{ title: string; className: string; }' is not assignable to type 'IntrinsicAttributes & SVGProps<SVGSVGElement> & { size?: string | number | undefined; className?: string | undefined; alt?: string | undefined; }'.
  Property 'title' does not exist on type 'IntrinsicAttributes & SVGProps<SVGSVGElement> & { size?: string | number | undefined; className?: string | undefined; alt?: string | undefined; }'.
```

**Comment by MattIPv4** [comment]
@pjeweb I think most of the icons here are behind admin things -- do you want to deploy this to preview and check things out?

**Comment by pjeweb** [comment]
> @pjeweb I think most of the icons here are behind admin things -- do you want to deploy this to preview and check things out?

i checked locally, looks good! do you want me to deploy it to preview for you to test? i use that for the discord PR right now...

**Review by pjeweb — APPROVED** [review]
lgtm

**Comment by MattIPv4** [comment]
If this looks go to you locally, sgtm. I also poked around locally and things looked fine.

**Pull request merged**
