### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by JonasFranke**
## Describe your changes

Update every dependency

## Notes for testing your change

Check apps work as expected

### CODE REVIEW

**Comment by MattIPv4** [comment]
👋 @JonasFranke what's the latest on this PR?

**Comment by JonasFranke** [comment]
> 👋 @JonasFranke what's the latest on this PR?

👋 I'm currently testing!

**Comment by JonasFranke** [comment]
There aren't any breaking changes. In my tests everything worked!

**Comment by pjeweb** [comment]
So I took a look at this again. I think we aren't really ready to migrate to biome while the import ordering rules are so limited. They seem to be working on it though: https://github.com/biomejs/biome/discussions/3015

I started to remodel your PR into one only apply the code style fixes for now, so we do not lose them in #743.

One of the next steps might be to clean up _this_ PR by rebasing and disabling the simplified import order rule we currently have enabled. That should make this PR a lot smaller.

Then we can discuss again if we want to swap to biome now or wait for more rules.

Also again sorry for our slow response time and slow reviews.

**Comment by MattIPv4** [comment]
Unfortunately, rather outdated at this point, closing.

**Pull request closed without merging**
