### PR TITLE
Use fallback image for transparent WebM in Safari

### LINKED ISSUE #698: [Idea]: Replace Animated Webp Bell Peepo on Updates Page With Video or Still Image
### Describe your idea / enhancement

The animated webp is pretty huge and apparently has problems playing at the correct fps. I would suggest replacing it with a webm video (~80% smaller) and fall back to a simple image. Maybe even supporting `prefers-reduced-motion`/`prefers-reduced-data`. I would not bother with HEVC + Alpha for older iOS.

### How would this idea / enhancement be beneficial?

Reduce bandwidth usage (for us and the users) - maybe even page responsiveness, improve accessibility.

### PR DESCRIPTION
**Pull request by pjeweb**
## Describe your changes

Use fallback image for transparent WebM in Safari cause it plays back bad (frame rate and missing transparency).

Fixes #698 

## Notes for testing your change

This time check more browsers ;)

### CODE REVIEW

**Review by MattIPv4 — COMMENTED** [review]
This doesn't seem to fix the issue on mobile? All iOS browsers seem to fail to render WebM in the same way?

**Comment by pjeweb** [comment]
> This doesn't seem to fix the issue on mobile? All iOS browsers seem to fail to render WebM in the same way?

Well it does not fix it, it just does not load the video

**Comment by pjeweb** [comment]
Oh you mean Chrome on iOS. So we should check OS instead of Browser, yeah?

**Comment by MattIPv4** [comment]
Yeh -- all browsers on iOS are webkit under the hood, so they're all going to have the same rendering issue. So I think we need the UA check for Safari on desktop, and then detecting iOS as a whole for mobile.

**Comment by MattIPv4** [comment]
Honestly part of me wonders if we should just choose a nice static frame and do away with this animation given how much of a headache it has been.

**Comment by pjeweb** [comment]
> Honestly part of me wonders if we should just choose a nice static frame and do away with this animation given how much of a headache it has been.

I still like it. Having it on the major desktop browsers and android seems like a win to me.

**Review by MattIPv4 — APPROVED** [review]

**Pull request merged**
