### PR TITLE
Use shared data for builds

### PR DESCRIPTION
**Pull request by MattIPv4**

### CODE REVIEW

**Comment by pjeweb** [comment]
what do you think about publishing the data as `@alveusgg/data` on npm, transpilied as js+d.ts? then we could skip the build step and git checkout?

**Comment by MattIPv4** [comment]
That makes senes to me -- do you want to take a look at doing that over in the data repo, and I'll fix up this build issue?

**Comment by pjeweb** [comment]
yeah i'll take a stab at it

**Review by pjeweb — APPROVED** [review]
fabulous

**Pull request merged**
